### PR TITLE
Fix screen capture capabilities detection and rename "webcam" to "camera" on mobile devices

### LINKED ISSUE #83: Screen recording non-functional on mobile devices
While it may be impossible to add screen recording to mobile devices for technical reasons, we must not offer this option in such a case. Right now, that's the first option users are presented with and clicking this makes the tool look like it's just completely broken.

### LINKED ISSUE #210: Use "Share camera" instead of "Share webcam" on mobile devices
Otherwise we could confuse users, as a phone's cameras are rarely called "webcams".

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
Fixes #210 
Fixes #83 

Those commits were already created before learning about your preference to have one PR per issue fix. They are semi-connected though so I combined them all in this PR. Reviewing the commits individually might be useful tho.

Regarding testing screen recording capabilities: I tested this on Safari IOS, Android Firefox & Chrome and on Desktop Firefox.

### CODE REVIEW

File: src/ui/media-devices.js [hunk 1]
```diff
@@ -78,17 +75,17 @@ function MediaDevices(props) {
         />
       )}
 
-      {supportsUserCapture() && (
+      {isUserCaptureSupported() && (
         <MediaDevice
           onClick={requestUserMedia}
-          title={t('share-webcam')}
+          title={onMobileDevice() ? t('share-camera') : t('share-webcam')}
```
Comment (luniki) [inline src/ui/media-devices.js]: I do not think that this is necessary. Always use one of the strings.

Comment (LukasKalbertodt) [reply src/ui/media-devices.js]: Lars mentioned that too. I still think "webcam" is slightly more clear on desktop, but I changed it now.
