### PR TITLE
Fix "black video preview" bug in mobile Firefox

### LINKED ISSUE #74: Black result preview in Firefox on Android
In Firefox on Android, the image representing the resulting media is often just black. Sometimes, this issue gets resolved when interacting with the site (pinch-zooming, rotating, …)

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
Fixes #74 

While debugging this, I found nothing wrong with the way the `<video>` is used currently. So it might be a bug in Firefox, but probably I'm missing something else still. This PR basically just contains a workaround, but I think it kind of makes sense. But if you think it's too hacky, we can of course not merge this.

### CODE REVIEW

File: src/ui/recording-preview.js [hunk 1]
```diff
@@ -38,6 +38,11 @@ const RecordingPreview = ({ deviceType, title, type, url }) => {
           transform: 'translate(-50%, -50%)'
         }}
         src={url}
+
+        // Without this, some browsers show a black video element instead of the first frame.
```
Comment (luniki) [inline src/ui/recording-preview.js]: Just drop the comments.

Comment (LukasKalbertodt) [reply src/ui/recording-preview.js]: Why exactly? If I were to encounter the line of code I've added, I would be confused. The line is not really self-explaining and seems redundant, so I think a comment is useful here. Maybe I'm missing something...

Comment (luniki) [reply src/ui/recording-preview.js]: Did you find a bug report for this? Why not link to this? 

I should have added my comment two lines down after these 2 not very useful ones:
```
    // onLoadedMetadata={e => e.target.currentTime = 0}
     // onLoadedData={e => e.target.currentTime = 0}
```

BTW generally React does not like this style of comments. See here:

https://reactjs.org/docs/faq-build.html#how-can-i-write-comments-in-jsx

Comment (LukasKalbertodt) [reply src/ui/recording-preview.js]: Oh gosh how did I miss these two useless lines? Sorry, of course, those comments are useless. Thanks for catching!

> Did you find a bug report for this?

Unfortunately, I did not.

Comment (LukasKalbertodt) [reply src/ui/recording-preview.js]: > BTW generally React does not like this style of comments. See here:

I found that, too, but interestingly, this leads to parsing errors for me. Not sure why.

```
./src/ui/recording-preview.js
  Line 42:98:  Parsing error: Unexpected token, expected "..."

  40 |         src={url}
  41 | 
> 42 |         {/* Without this, some browsers show a black video element instead of the first frame. */}
     |                                                                                                  ^
```

Comment (luniki) [reply src/ui/recording-preview.js]: Comments must be outside of tags. That's all :-)

Comment (LukasKalbertodt) [reply src/ui/recording-preview.js]: Oh ok. Would you prefer me to change it?

**Comment by luniki** [comment]
Go for it!
