### PR TITLE
Fix safari not capturing both display and camera

### LINKED ISSUE #934: Capturing "Display & Camera" does not work in Safari (macOS)
When pressing the "Display & Capture"-button in Safari on macOS I'm not asked for permission to share my screen. Instead, I see the following error.

image

Camera capture works just fine, as does capturing *only* the screen (using the "Display" button in the first step).

The following error is logged to the console on the screen seen in the screenshot:

```
[Error] Error: InvalidAccessError: getDisplayMedia must be called from a user gesture handler.
	(anonymous function) (2.859294be.chunk.js:2:305924)
	(anonymous function) (4.58adb615.chunk.js:1:12044)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
```

(Everything tested on https://studio.opencast.org.)

### PR DESCRIPTION
**Pull request by owi92**
Safari needs a "user gesture" (i.e. a button click) to call `getDisplayMedia`. Calling the user capture first would prevent the display capture to register the triggering button click, so this switches the ordering (for safari only).
So in Safari, the user will always get asked to share their screen before they get asked to share their webcam.

(I did notice that when calling both `startUserCapture` and `startDisplayCapture` inside a `Promise.all()`, the ordering in Safari is consistently switched again, but with no issues (meaning user capture is asked before screen capture). This would be preferrable, but I'm not sure if we can rely on this always being the case. So in the interest of consistency I chose to just call `startDisplayCapture` first...)

Closes #934

### CODE REVIEW

File: src/steps/video-setup/source-select.tsx [hunk 1]
```diff
@@ -44,11 +44,20 @@ export const SourceSelection: React.FC<SourceSelectionProps> = ({
...
     setActiveSource("both");
-    await startUserCapture(dispatch, settings, userConstraints);
-    await Promise.all([
-      queryMediaDevices(dispatch),
-      startDisplayCapture(dispatch, settings, displayConstraints),
-    ]);
+    // Safari needs the display capture to be called first as
+    // otherwise `getDisplayMedia` won't register the button click and
+    // throw an error.
+    if (navigator.userAgent.match(/safari/i) && !navigator.userAgent.match(/chrome/i)) {
```
Comment (LukasKalbertodt) [inline src/steps/video-setup/source-select.tsx:50]: We do have the `onSafari` helper function in `util/index.tsx`. You can probably use that?

File: src/steps/video-setup/source-select.tsx [hunk 2]
```diff
@@ -44,11 +44,20 @@ export const SourceSelection: React.FC<SourceSelectionProps> = ({
...
   const clickBoth = async () => {
     setActiveSource("both");
-    await startUserCapture(dispatch, settings, userConstraints);
-    await Promise.all([
-      queryMediaDevices(dispatch),
-      startDisplayCapture(dispatch, settings, displayConstraints),
-    ]);
+    // Safari needs the display capture to be called first as
+    // otherwise `getDisplayMedia` won't register the button click and
+    // throw an error.
```
Comment (LukasKalbertodt) [inline src/steps/video-setup/source-select.tsx:49]:
```suggestion
    // Safari needs the display capture to be called first as otherwise
    // it thinks `getDisplayMedia` is called without user gesture and
    // throws an error.
```

Mentioning "user gesture" here is probably a good idea.

**Review by LukasKalbertodt — CHANGES_REQUESTED** [review]
This PR having two commits is certainly unexpeted.

Thanks! Just two tiny things.

File: src/steps/video-setup/source-select.tsx (hunk 1 above)
Comment (owi92) [reply src/steps/video-setup/source-select.tsx]: Nice, that certainly is a useful helper^^

**Comment by lkiesow** [comment]
I'm wondering if the code for Safari wouldn't actually work on in all major vrowsers.
Do we really need two code branches here?

**Comment by LukasKalbertodt** [comment]
It's complicated. The current order was specifically chosen in commit 66865d3609348c17af51a9aab20bf5fda654dafc

> Request webcam before display share
>
> If sharing a specific window from the desktop, some browsers bring that window into the foreground. If it does not overlap the browser window, users might be confused as the webcam is not requested. This only happens after the browser window is focused again. Changing the order works around this problem.

Once we fix #403 is fixed, we might be able to remove the extra branch here. The branch is annoying but we didn't want to risk maybe making the workflow for some people worse. Or well, just changing anything might annoy people.
