### PR TITLE
Improve settings, OC connection warning and fix menu bug

### LINKED ISSUE #373: Missing "Cancel" button on /settings
There is currently no button to dismiss the settings page.

### LINKED ISSUE #375: Warning on missings settings.json
Currently there is a warning of a missing settings.json even if we are running in standalone mode. As there are currently no consequences to a missing settings file this warning should be muted too.

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
Fixes #375 

A few small things. Most importantly: the "no OC connection setting" is not shown everywhere anymore. Instead it is only shown in the post-recording dialog:

Screenshot from 2020-01-28 14-25-40

When clicking the "settings" link in the warning or the menu, the settings page is shown. After the user saved and we validated an opencast connection, this is shown:

Screenshot from 2020-01-28 14-26-15

This special "back" link is only shown if the user already recorded something.

I would say this closes #373. But @lkiesow @luniki tell me if you are happy with this solution.

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ function App({ settingsManager }) {
 
             <Switch>
               <Route path="/settings" exact>
-                <SettingsPage settingsManager={settingsManager} />
+                <SettingsPage settingsManager={settingsManager} hasRecording={activeStep === 3}/>
```
Comment (luniki) [inline src/App.js]: I do not think that the SettingsPage should know about some active step number of another page. This way the state is all over the place and I would prefer to do in another way.

File: src/ui/navigation.js [hunk 2]
```diff
@@ -71,6 +71,7 @@ const NavElement = ({ target, children, icon, ...rest }) => {
 const Navigation = props => {
   const [isOpened, updateIsOpened] = useState(false);
   const toggleMenu = () => updateIsOpened(!isOpened);
+  const closeMenu = () => updateIsOpened(false);
```
Comment (luniki) [inline src/ui/navigation.js]: Could you explain the original problem resulting in these changes?

File: src/ui/settings/opencast.js [hunk 3]
```diff
@@ -113,6 +114,9 @@ function OpencastSettings({ settingsManager }) {
               sx={{ ml: '10px', fontSize: '30px', verticalAlign: 'middle' }}
               spin={status === 'testing'}
             /> }
+            { hasRecording && status === 'saved' && (
+              <Link to="/" sx={{ ml: 3 }}>{t('settings-back-to-recording')}</Link>
```
Comment (luniki) [inline src/ui/settings/opencast.js]: You should add "variant: 'styles.a'" to the sx attribute to style the link as defined in the theme.

File: src/ui/settings/page.js [hunk 4]
```diff
@@ -3,25 +3,26 @@
...
 
 
-const SettingsPage = ({ settingsManager }) => {
+const SettingsPage = ({ settingsManager, hasRecording }) => {
+  console.log(hasRecording);
   const { t } = useTranslation();
 
   return (
-    <Container sx={{ p: 3 }}>
+    <Box sx={{ width: '100%', maxWidth: 960, mx: 'auto', p: 3 }}>
```
Comment (luniki) [inline src/ui/settings/page.js]: Is this a regression? Shouldn't this be a Container?

File: src/ui/settings/page.js [hunk 5]
```diff
@@ -3,25 +3,26 @@
...
-import { Container } from '@theme-ui/components';
+import { Box } from '@theme-ui/components';
 
 import LanguageSettings from './language';
 import OpencastSettings from './opencast';
 
 
-const SettingsPage = ({ settingsManager }) => {
+const SettingsPage = ({ settingsManager, hasRecording }) => {
+  console.log(hasRecording);
```
Comment (luniki) [inline src/ui/settings/page.js]: console.log...

Comment (luniki) [reply src/ui/settings/page.js]: Instead of providing "hasRecording" as a prop you could just ask for the recording context:

```import { useRecordingState } from '../../recording-context';```

and

```  
const { recordings } = useRecordingState();
const hasRecording = recordings.length;
```

File: src/ui/studio/save-creation/index.js [hunk 6]
```diff
@@ -179,6 +180,14 @@ export default function SaveCreation(props) {
           }
         }}
       >
+        {!uploadPossible && (
+          <Notification key="opencast-connection" isDanger>
+            <Trans i18nKey="warning-missing-connection-settings">
+              Warning. <Link to="/settings">setting</Link>
```
Comment (luniki) [inline src/ui/studio/save-creation/index.js]: Another Link that has to be styled with sx={{ variant: "styles.a" }}

File: src/ui/navigation.js (hunk 2 above)
Comment (LukasKalbertodt) [reply src/ui/navigation.js]: When the browser was wide enough for the non-mobile menu, clicking a nav item once would result in the "opened" state being toggled. Meaning that it was then "opened". Switching to the mobile view (e.g. by making your browser window smaller or turning your phone) would then have the menu half open when it should be closed. The actual nav items should only ever close the menu, never open it, so this is semantically more correct even.

File: src/ui/settings/page.js (hunk 4 above)
Comment (LukasKalbertodt) [reply src/ui/settings/page.js]: That's actually intended as `Container` is very wide. Looks pretty bad IMO when input boxes are 1400px or so wide. Using `Container` and still specifying a `maxWidth` doesn't work.
